In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [3]:
from sklearn.datasets import make_classification

In [4]:
x,y = make_classification(n_classes=2,n_features=4,n_samples=500,random_state=0)

In [5]:
x

array([[-0.34917739, -0.7204688 , -0.65302064,  0.0464621 ],
       [-2.15244896, -0.62458631, -2.48316375,  0.42196891],
       [ 1.93033293, -0.04146763,  1.98381669, -0.39979292],
       ...,
       [-0.09440045,  0.44229321,  0.08089276,  0.03518888],
       [ 0.91181228,  0.75402614,  1.24968892, -0.16136869],
       [ 0.51745152,  1.11257209,  0.98586466, -0.06725822]])

In [6]:
y

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
x_train.shape

(400, 4)

In [11]:
x_test.shape

(100, 4)

In [12]:
import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential([
    Dense(10,activation='relu',input_shape=[4]),
    Dense(10,activation='relu'),
    Dense(10,activation='relu'),
    Dense(1,activation='sigmoid')
])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 281
Trainable params: 281
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
13/13 [==============================] - 2s 5ms/step - loss: 0.7779 - accuracy: 0.4500
Epoch 2/100
13/13 [==============================] - 0s 4ms/step - loss: 0.7245 - accuracy: 0.4450
Epoch 3/100
13/13 [==============================] - 0s 4ms/step - loss: 0.6832 - accuracy: 0.4575
Epoch 4/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6447 - accuracy: 0.4625
Epoch 5/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6091 - accuracy: 0.5475
Epoch 6/100
13/13 [==============================] - 0s 3ms/step - loss: 0.5754 - accuracy: 0.6625
Epoch 7/100
13/13 [==============================] - 0s 4ms/step - loss: 0.5493 - accuracy: 0.7900
Epoch 8/100
13/13 [==============================] - 0s 3ms/step - loss: 0.5294 - accuracy: 0.8175
Epoch 9/100
13/13 [==============================] - 0s 4ms/step - loss: 0.5131 - accuracy: 0.8375
Epoch 10/100
13/13 [==============================] - 0s 3ms/step - loss: 0.4993 - accuracy: 0.8400
Epoch 11/

13/13 [==============================] - 0s 4ms/step - loss: 0.2346 - accuracy: 0.9200
Epoch 84/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2334 - accuracy: 0.9150
Epoch 85/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2323 - accuracy: 0.9175
Epoch 86/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2305 - accuracy: 0.9175
Epoch 87/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2303 - accuracy: 0.9200
Epoch 88/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2269 - accuracy: 0.9200
Epoch 89/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2271 - accuracy: 0.9175
Epoch 90/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2254 - accuracy: 0.9200
Epoch 91/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2241 - accuracy: 0.9200
Epoch 92/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2224 - accuracy: 0.9175
Epoch 93/100


In [17]:
y_pred = model.predict(x_test)

In [18]:
y_pred

array([[0.07815118],
       [0.5590684 ],
       [0.654443  ],
       [0.984608  ],
       [0.45325658],
       [0.9999976 ],
       [0.7211372 ],
       [0.0833114 ],
       [0.02803041],
       [0.24849921],
       [0.7212349 ],
       [0.9999982 ],
       [0.68122774],
       [0.03533466],
       [0.9999385 ],
       [0.99863005],
       [1.        ],
       [0.7147722 ],
       [0.01801734],
       [0.999757  ],
       [1.        ],
       [0.99823344],
       [0.99944514],
       [0.01999638],
       [0.06397747],
       [0.72719985],
       [0.7148487 ],
       [0.549112  ],
       [0.05723181],
       [0.07149471],
       [0.05817626],
       [0.54111814],
       [0.08148411],
       [0.5402412 ],
       [0.50964546],
       [0.0360637 ],
       [0.99824715],
       [0.12571673],
       [0.9941294 ],
       [0.05248965],
       [0.03423592],
       [1.        ],
       [0.06703964],
       [0.01314706],
       [0.02334297],
       [0.01864545],
       [0.999941  ],
       [0.116

In [19]:
y_pred = y_pred.round()
y_pred

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [20]:
from sklearn.metrics import confusion_matrix,classification_report

In [21]:
print(confusion_matrix(y_test,y_pred))

[[43  8]
 [ 3 46]]


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.84      0.89        51
           1       0.85      0.94      0.89        49

    accuracy                           0.89       100
   macro avg       0.89      0.89      0.89       100
weighted avg       0.89      0.89      0.89       100

